version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clean_energy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5454:5432"
    networks:
      - app_network

  app:
    build: .
    container_name: clean_energy_app
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/clean_energy"
      NEXTAUTH_SECRET: "p0bmfAJFAos0922d"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: >
      sh -c "
      npx prisma migrate deploy && npx prisma db seed && npm start"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
